name: Playwright Tests
on: #trigger -- comandos/condicoes que inicializam o test script nessas branches (push and pull_request)
  push:
    branches: [ main, master ] 
  pull_request:
    branches: [ main, master ]
jobs: # tarefas que devem ser executadas
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest #nessa etapa que defique onde vai rodar os testes Ex: Docker (onde vai rodar o teste?) agente de execuçao
    steps: #uses: ativando pluging no github actions
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4 #comenta o artefato encontrado no report
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
